version: '3'
services:
  live-reload:
    image: openjdk:8-jdk-alpine
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: './mvnw spring-boot:run'